### ISSUE TITLE
Terminate workers on destroy

### ISSUE THREAD

**Issue by yairtawil** [tschaub/pixelworks#74]
hi, 

Even after calling `processor.destroy()`:
```javascript

Processor.prototype.destroy = function() {
  for (var key in this) {
    this[key] = null;
  }
  this._destroyed = true;
};

```
workers threads are still alive...
`worker.terminate()` will kill all the workers

**Comment by EvertEt** [comment]
@yairtawil I am seeing problems related to this using openlayers. Do you know of any workaround?
