### ISSUE TITLE
Passing function imported from a module to the lib so workers can use it

### ISSUE THREAD

**Issue by shaunakv1** [tschaub/pixelworks#81]
Hi @tschaub 

I have a module defined like so:

> color-math.js

```
module.exports = {

    lab2rgb: function (lab) {
        //removed for brevity
    },

    rgb2lab: function (rgb) {
        //removed for brevity
    },

    /**
     * // calculate the perceptual distance between colors in CIELAB
     * @param {} labA color value
     * @param {} labB color value
     */
    deltaE: function (labA, labB) {
        //removed for brevity
    },

    /**
    * pixelMatches Takes two rgb pixels and checks if they match
    */
    pixelMatches: function (pixel1rgb, pixel2rgb) {
        var pixel1Lab = rgb2lab(pixel1rgb);
        var pixel2Lab = rgb2lab(pixel2rgb);
        var diff = deltaE(pixel1Lab, pixel2Lab);
        if (diff < 3.0) return true;
        else return false;
    }
}
```

Which gets used in an OpenLayers `RasterSource` like so:

```
import { rgb2lab, lab2rgb, deltaE, pixelMatches } from "../lib/color-math";

this.landCoverChangeRasterSource = new RasterSource({
      sources: [this.landCoverLayers[1996], this.landCoverLayers[2010]],
      operation: (pixels, data) => {
        const R = 0, G = 1, B = 2, A = 3;
        let pixel1 = pixels[0];
        let pixel2 = pixels[1];
        if (pixel1[A] > 0 && pixel2[A] > 0 && !pixelMatches(pixel1, pixel2)) {  //<---ERRORS Here
          return [255, 0, 0, 255];
        }
        else
          return [0, 0, 0, 0]
      },
      lib: {
        rgb2lab: rgb2lab,
        lab2rgb: lab2rgb,
        deltaE: deltaE,
        pixelMatches: pixelMatches
      }
    });
```

When I pass the imported color math functions to  the worker using `lib` like shown above, it errors out with `_colorMath is not defined`

![image](https://user-images.githubusercontent.com/732604/62673115-2d0d5b00-b96b-11e9-9042-399c248f8408.png)

Clearly it's related to how the reference to the functions is passed to the workers. Is there anyway I can accomplish this or is this just a restriction of how the functions need to be passed?
I have a whole bunch of functions I need to use, which if all defined with the map code will be hard to manage. 

If I define all those functions in same scope as the where the layer is defined and then pass it to lib it works just fine as you can see in some examples here: 

https://shaunakv1.github.io/OpenLayers3_Raster_Manipulation_Examples/

and code here: 

https://github.com/shaunakv1/OpenLayers3_Raster_Manipulation_Examples/blob/master/js/landcover_change_by_class.html.js

**Comment by tschaub** [comment]
Without digging into it, it looks like this is about how your bundler is renaming functions in `color-math.js`.  You may have better luck with something like:
```js
function rgb2lab(rgb) {
  // etc.
}

function pixelMatches(pixel1rgb, pixel2rgb) {
  var pixel1Lab = rgb2lab(pixel1rgb);
  // etc.
}

exports.pixelMatches = pixelMatches;
exports.rgb2lab = rgb2lab;
```js

But these functions too may be renamed when bundling or minifying.  If you look at the source for your worker, you can find out what the functions look like when stringified (this lib is just calling `fn.toString()` on them).

**Comment by shaunakv1** [comment]
@tschaub you are correct. Problem is that the minifier cannot recognize that the function being called inside the operation function is the same as the one passed via the lib. It does the renaming correctly, but goofs up the actual call.

The reason I don't want to define the functions in the same scope is because they are quite complex and just mucks up the file. 

I ended up solving this by using `eval` inside the operation function like below. Is there a way to do this cleaner?  Would it be possible to pass the lib to it, just like we pass the `data` ? that way the compiler can make the connection and rename correctly. 

```js
import { rgb2lab, lab2rgb, deltaE, pixelMatches } from "../lib/color-math";

this.landCoverChangeRasterSource = new RasterSource({
      sources: [this.landCoverLayers[1996], this.landCoverLayers[2010]],
      operation: (pixels, data) => {
        const R = 0, G = 1, B = 2, A = 3;
        let pixel1 = pixels[0];
        let pixel2 = pixels[1];
        if (pixel1[A] > 0 && pixel2[A] > 0 && !eval("pixelMatches")(pixel1, pixel2)) {  //<--- FIXED!
          return [255, 0, 0, 255];
        }
        else
          return [0, 0, 0, 0]
      },
      lib: {
        rgb2lab: rgb2lab,
        lab2rgb: lab2rgb,
        deltaE: deltaE,
        pixelMatches: pixelMatches
      }
    });
```

**Comment by tschaub** [comment]
Not sure there is a great solution for this.
