### ISSUE TITLE
Using angular 7+ universal with Openlayers 5+

### ISSUE THREAD

**Issue by philip-firstorder** [tschaub/pixelworks#83]
**Problem**
https://stackoverflow.com/questions/55120373/using-angular-7-universal-with-openlayers-5

I've got an angular 7+ app using open layers 5+. I'm trying to set up angular universal for this app, but when I run the universal server (node dist/server.js), I got some errors due to client only variables not being defined, such as window.

```bash
webpack:///./node_modules/ol/has.js?:54
var DEVICE_PIXEL_RATIO = window.devicePixelRatio || 1;
                     ^
ReferenceError: window is not defined
```

I solved this using domino to mock these variables, but it just fails with another error, because of a canvas element

```bash
Error: NotYetImplemented
   at HTMLCanvasElement.exports.nyi (/my/project/dist/server.js)
```

The error is caused by the pixelworks library, which is a dependency of OL 5+.

This library instantiates a canvas and tries to get a 2d context from it, which is not supported by domino

https://github.com/tschaub/pixelworks/blob/02920ad6bc1a1058680b4c67aeee1e07029b635f/lib/util.js#L8

The context is not used straight away, but is created at a place where it is always instantiated.

**Temporary solution**
Since I do not want to use OL when the code is executed server side, my solution (hack) was to modify the server.js file during the build process to remove this instantiation.

```bash
sed -i "s/var context = document.createElement('canvas').getContext('2d');/var context = null;/" dist/server.js
```

**Expected**
A better solution is to modify the [pixelworks line](https://github.com/tschaub/pixelworks/blob/02920ad6bc1a1058680b4c67aeee1e07029b635f/lib/util.js#L8) causing the problem to declare the context as null if it cannot be created, either because document or canvas or getContext are not defined.

```js
var context = null;
try {
  context = document.createElement('canvas').getContext('2d');
}
catch (e) {
  // Do nothing
}
```

**Comment by werrolf** [comment]
This isn't specific to Angular nor Openlayers. The assumption that there is a browser providing a document at import time is dangerous in general.

I ended up with this:

```patch
--- ../node_modules/pixelworks/lib/util.js.original	2020-06-05 10:17:24.755668818 +0200
+++ ../node_modules/pixelworks/lib/util.js	2020-06-05 10:18:27.487757907 +0200
@@ -5,12 +5,13 @@
   hasImageData = false;
 }
 
-var context = document.createElement('canvas').getContext('2d');
+var context;
 
 function newImageData(data, width, height) {
   if (hasImageData) {
     return new ImageData(data, width, height);
   } else {
+    context = context || document.createElement('canvas').getContext('2d');
     var imageData = context.createImageData(width, height);
     imageData.data.set(data);
     return imageData;
```

The fallback from ImageData to canvas is intact, but canvas instantiation is deferred until first use.

I encountered this while building a single-file ~ES5 dump for browser consumption, using rollup. But again, I think this is a general blemish which may cause problems in many different scenarios.
